// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cardapio_digital;

#nullable disable

namespace cardapio_digital.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812221407_RenomendoPortuguesPraEnglish")]
    partial class RenomendoPortuguesPraEnglish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cardapio_digital.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_categories_school_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_children");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_children_parent_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_children_school_id");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_menus");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_menus_school_id");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.MenuProduct", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("MenuId", "ProductId")
                        .HasName("pk_menu_products");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_menu_products_product_id");

                    b.ToTable("menu_products", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_parents");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_parents_user_id");

                    b.ToTable("parents", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_products_school_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Shifts")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shifts");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_schools");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_schools_user_id");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Category", b =>
                {
                    b.HasOne("cardapio_digital.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Child", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_children_parents_parent_id");

                    b.HasOne("cardapio_digital.Entities.School", "School")
                        .WithMany("Children")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_children_schools_school_id");

                    b.Navigation("Parent");

                    b.Navigation("School");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Menu", b =>
                {
                    b.HasOne("cardapio_digital.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menus_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("cardapio_digital.Entities.MenuProduct", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_products_menus_menu_id");

                    b.HasOne("cardapio_digital.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_products_products_product_id");

                    b.Navigation("Menu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Parent", b =>
                {
                    b.HasOne("cardapio_digital.Entities.User", "User")
                        .WithOne("Parent")
                        .HasForeignKey("cardapio_digital.Entities.Parent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parents_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Product", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.HasOne("cardapio_digital.Entities.School", "School")
                        .WithMany("Products")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_schools_school_id");

                    b.Navigation("Category");

                    b.Navigation("School");
                });

            modelBuilder.Entity("cardapio_digital.Entities.School", b =>
                {
                    b.HasOne("cardapio_digital.Entities.User", "User")
                        .WithOne("School")
                        .HasForeignKey("cardapio_digital.Entities.School", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schools_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("cardapio_digital.Entities.School", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("cardapio_digital.Entities.User", b =>
                {
                    b.Navigation("Parent")
                        .IsRequired();

                    b.Navigation("School")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
