// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cardapio_digital;

#nullable disable

namespace cardapio_digital.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723145527_AjustarDataNascimentoFilho")]
    partial class AjustarDataNascimentoFilho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cardapio_digital.Entities.Cardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EscolaId")
                        .HasColumnType("integer")
                        .HasColumnName("escola_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cardapios");

                    b.HasIndex("EscolaId")
                        .HasDatabaseName("ix_cardapios_escola_id");

                    b.ToTable("cardapios", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.CardapioProduto", b =>
                {
                    b.Property<int>("CardapioId")
                        .HasColumnType("integer")
                        .HasColumnName("cardapio_id");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.HasKey("CardapioId", "ProdutoId")
                        .HasName("pk_cardapio_produtos");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_cardapio_produtos_produto_id");

                    b.ToTable("cardapio_produtos", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Escola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("Turnos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turnos");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_escolas");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_escolas_usuario_id");

                    b.ToTable("escolas", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Filho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<int>("EscolaId")
                        .HasColumnType("integer")
                        .HasColumnName("escola_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer")
                        .HasColumnName("pais_id");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_filhos");

                    b.HasIndex("EscolaId")
                        .HasDatabaseName("ix_filhos_escola_id");

                    b.HasIndex("PaisId")
                        .HasDatabaseName("ix_filhos_pais_id");

                    b.ToTable("filhos", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_pais");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_pais_usuario_id");

                    b.ToTable("pais", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric")
                        .HasColumnName("preco");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_produtos_categoria_id");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Cardapio", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cardapios_escolas_escola_id");

                    b.Navigation("Escola");
                });

            modelBuilder.Entity("cardapio_digital.Entities.CardapioProduto", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Cardapio", "Cardapio")
                        .WithMany()
                        .HasForeignKey("CardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cardapio_produtos_cardapios_cardapio_id");

                    b.HasOne("cardapio_digital.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cardapio_produtos_produtos_produto_id");

                    b.Navigation("Cardapio");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Escola", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Usuario", "Usuario")
                        .WithOne("Escola")
                        .HasForeignKey("cardapio_digital.Entities.Escola", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escolas_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Filho", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Escola", "Escola")
                        .WithMany("Filhos")
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_filhos_escolas_escola_id");

                    b.HasOne("cardapio_digital.Entities.Pais", "Pais")
                        .WithMany("Filhos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_filhos_pais_pais_id");

                    b.Navigation("Escola");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Pais", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Usuario", "Usuario")
                        .WithOne("Pais")
                        .HasForeignKey("cardapio_digital.Entities.Pais", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pais_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Produto", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Escola", b =>
                {
                    b.Navigation("Filhos");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Pais", b =>
                {
                    b.Navigation("Filhos");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Usuario", b =>
                {
                    b.Navigation("Escola")
                        .IsRequired();

                    b.Navigation("Pais")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
