// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cardapio_digital;

#nullable disable

namespace cardapio_digital.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803224311_AdicionarEscolaIdCategoria")]
    partial class AdicionarEscolaIdCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cardapio_digital.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EscolaId")
                        .HasColumnType("integer")
                        .HasColumnName("escola_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cardapios");

                    b.HasIndex("EscolaId")
                        .HasDatabaseName("ix_cardapios_escola_id");

                    b.ToTable("cardapios", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.MenuProduct", b =>
                {
                    b.Property<int>("CardapioId")
                        .HasColumnType("integer")
                        .HasColumnName("cardapio_id");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.HasKey("CardapioId", "ProdutoId")
                        .HasName("pk_cardapio_produtos");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_cardapio_produtos_produto_id");

                    b.ToTable("cardapio_produtos", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EscolaId")
                        .HasColumnType("integer")
                        .HasColumnName("escola_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("EscolaId")
                        .HasDatabaseName("ix_categorias_escola_id");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("Shifts")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turnos");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_escolas");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_escolas_usuario_id");

                    b.ToTable("escolas", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<int>("EscolaId")
                        .HasColumnType("integer")
                        .HasColumnName("escola_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("pai_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_filhos");

                    b.HasIndex("EscolaId")
                        .HasDatabaseName("ix_filhos_escola_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_filhos_pai_id");

                    b.ToTable("filhos", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_pais");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_pais_usuario_id");

                    b.ToTable("pais", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<int>("EscolaId")
                        .HasColumnType("integer")
                        .HasColumnName("escola_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric")
                        .HasColumnName("preco");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_produtos_categoria_id");

                    b.HasIndex("EscolaId")
                        .HasDatabaseName("ix_produtos_escola_id");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perfil");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("cardapio_digital.Entities.Menu", b =>
                {
                    b.HasOne("cardapio_digital.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cardapios_escolas_escola_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("cardapio_digital.Entities.MenuProduct", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("CardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cardapio_produtos_cardapios_cardapio_id");

                    b.HasOne("cardapio_digital.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cardapio_produtos_produtos_produto_id");

                    b.Navigation("Menu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Category", b =>
                {
                    b.HasOne("cardapio_digital.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorias_escolas_escola_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("cardapio_digital.Entities.School", b =>
                {
                    b.HasOne("cardapio_digital.Entities.User", "User")
                        .WithOne("School")
                        .HasForeignKey("cardapio_digital.Entities.School", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escolas_usuarios_usuario_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Child", b =>
                {
                    b.HasOne("cardapio_digital.Entities.School", "School")
                        .WithMany("Children")
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_filhos_escolas_escola_id");

                    b.HasOne("cardapio_digital.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_filhos_pais_pai_id");

                    b.Navigation("School");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Parent", b =>
                {
                    b.HasOne("cardapio_digital.Entities.User", "User")
                        .WithOne("Parent")
                        .HasForeignKey("cardapio_digital.Entities.Parent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pais_usuarios_usuario_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Product", b =>
                {
                    b.HasOne("cardapio_digital.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_categorias_categoria_id");

                    b.HasOne("cardapio_digital.Entities.School", "School")
                        .WithMany("Products")
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_escolas_escola_id");

                    b.Navigation("Category");

                    b.Navigation("School");
                });

            modelBuilder.Entity("cardapio_digital.Entities.School", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("cardapio_digital.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("cardapio_digital.Entities.User", b =>
                {
                    b.Navigation("School")
                        .IsRequired();

                    b.Navigation("Parent")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}

